Strip binaries and enforce security policy

diff --git a/initrd/common/overlay-mount b/initrd/common/overlay-mount
--- a/initrd/common/overlay-mount
+++ b/initrd/common/overlay-mount
@@ -5,22 +5,34 @@ if [ "$1" != "recovery" ]; then
 	mkdir -p /rootfs-part
 	mkdir -p /overlaymount-rootfs
 	mount -t ext4 -o nosuid /dev/mmcblk0p3 /rootfs-part
-	/usr/bin/unsquashfs -f -d /key /opt/key.sqsh
-	/usr/bin/openssl dgst -sha256 -verify /key/public.pem -signature /rootfs-part/rootfs.squashfs.dgst /rootfs-part/rootfs.squashfs
+	/usr/bin/unsquashfs -f -d /key /opt/key.sqsh &>/dev/null
+	/usr/bin/openssl dgst -sha256 -verify /key/public.pem -signature /rootfs-part/rootfs.squashfs.dgst /rootfs-part/rootfs.squashfs &>/dev/null
+	echo "Verifying root filesystem's digital signature ..."
 	if [ $? != 0 ]; then
 		echo "Root filesystem's digital signature is invalid! Shutting down ..."
+		sync
 		umount /rootfs-part -l -f
 		busybox poweroff
 		exit 1
 	else
+		echo "Done."
 		# Some mountpoints
 		mkdir -p /rootfs-part/rootfs/read
 		mkdir -p /rootfs-part/rootfs/work
 		mkdir -p /rootfs-part/rootfs/write
 		mkdir -p /rootfs-part/rootfs/overlay
 
-		losetup /dev/loop1 /rootfs-part/overlaymount-rootfs.squashfs
-		mount /dev/loop1 /overlaymount-rootfs
+		/usr/bin/openssl dgst -sha256 -verify /key/public.pem -signature /rootfs-part/overlaymount-rootfs.squashfs.dgst /rootfs-part/overlaymount-rootfs.squashfs &>/dev/null
+		if [ $? != 0 ]; then
+			echo "Utility root filesystem's signature is invalid! Shutting down ..."
+			sync
+			umount /rootfs-part -l -f
+			busybox poweroff
+			exit 1
+		else
+			losetup /dev/loop1 /rootfs-part/overlaymount-rootfs.squashfs
+			mount /dev/loop1 /overlaymount-rootfs
+		fi
 
 		# Filesystems
 		mount -t devtmpfs devtmpfs /overlaymount-rootfs/dev
@@ -35,13 +47,13 @@ if [ "$1" != "recovery" ]; then
 		ln -s /overlaymount-rootfs/mnt/rootfs/overlay /mnt
 
 		busybox chroot /overlaymount-rootfs "/bin/squashfuse" "/mnt/rootfs-part/rootfs.squashfs" "/mnt/rootfs/read"
-		if [ "$1" == "ro" ]; then
-			if [ "$2" == "std" ]; then
+		if [ "${1}" == "ro" ]; then
+			if [ "${2}" == "std" ]; then
 				busybox chroot /overlaymount-rootfs "/bin/fuse-overlayfs" "-o" "ro,nosuid,lowerdir=/mnt/rootfs/read,upperdir=/mnt/rootfs/write,workdir=/mnt/rootfs/work" "/mnt/rootfs/overlay"
 			else
 				busybox chroot /overlaymount-rootfs "/bin/fuse-overlayfs" "-o" "ro,lowerdir=/mnt/rootfs/read,upperdir=/mnt/rootfs/write,workdir=/mnt/rootfs/work" "/mnt/rootfs/overlay"
 			fi
-		elif [ "$1" == "rw" ]; then
+		elif [ "${1}" == "rw" ]; then
 			busybox chroot /overlaymount-rootfs "/bin/fuse-overlayfs" "-o" "lowerdir=/mnt/rootfs/read,upperdir=/mnt/rootfs/write,workdir=/mnt/rootfs/work" "/mnt/rootfs/overlay"
 		else
 			echo "Invalid argument"
@@ -54,8 +66,18 @@ else
 	mkdir -p /overlaymount-rootfs
 	mount -t ext4 -o nosuid,ro /dev/mmcblk0p2 /recoveryfs-part
 
-	losetup /dev/loop1 /recoveryfs-part/overlaymount-rootfs.squashfs
-	mount /dev/loop1 /overlaymount-rootfs
+	/usr/bin/unsquashfs -f -d /key /opt/key.sqsh &>/dev/null
+	/usr/bin/openssl dgst -sha256 -verify /key/public.pem -signature /key/public.pem -signature /recoveryfs-part/overlaymount-rootfs.squashfs.dgst &>/dev/null
+	if [ $? != 0 ]; then
+		echo "Utility root filesystem's signature is invalid! Shutting down ..."
+		sync
+		umount -l -f /recoveryfs-part
+		busybox poweroff
+		exit 1
+	else
+		losetup /dev/loop1 /recoveryfs-part/overlaymount-rootfs.squashfs
+		mount /dev/loop1 /overlaymount-rootfs
+	fi
 
 	# Filesystems
 	mount -t devtmpfs devtmpfs /overlaymount-rootfs/dev
@@ -68,6 +90,17 @@ else
 	rm -r /mnt
 	ln -s /overlaymount-rootfs/mnt/recoveryfs /mnt
 
-	busybox chroot /overlaymount-rootfs "/bin/squashfuse" "/mnt/recoveryfs-part/recoveryfs.squashfs" "/mnt/recoveryfs"
+	echo "Verifying recovery filesystem's digital signature ..."
+	/usr/bin/openssl dgst -sha256 -verify /key/public.pem -signature /rootfs-part/recoveryfs.squashfs.dgst /rootfs-part/recoveryfs.squashfs &>/dev/null
+	if [ $? != 0 ]; then
+		echo "Recovery filesystem's digital signature is invalid! Shutting down ..."
+		sync
+		umount /rootfs-part -l -f
+		busybox poweroff
+		exit 1
+	else
+		echo "Done."
+		busybox chroot /overlaymount-rootfs "/bin/squashfuse" "/mnt/recoveryfs-part/recoveryfs.squashfs" "/mnt/recoveryfs"
+	fi
 fi
 
