Improved X11 extensions handling

diff --git a/initrd/common/startx b/initrd/common/startx
--- a/initrd/common/startx
+++ b/initrd/common/startx
@@ -1,11 +1,14 @@
-#!/bin/sh
+#!/bin/sh -x
 
 # Mounting a temporary procfs otherwise the mount process might not work
 mount -t proc proc /proc
 
 mkdir -p /mnt/xorg
 mkdir -p /mnt/opt/X11/base/rootfs
-mkdir -p /mnt/opt/X11/extensions/merged
+mkdir -p /mnt/opt/X11/extensions-user
+mkdir -p /mnt/opt/X11/extensions-base
+mkdir -p /mnt/opt/X11/extension-storage-merged
+mkdir -p /mnt/opt/X11/extensions-merged
 mkdir -p /mnt/opt/X11/rootfs/write
 mkdir -p /mnt/opt/X11/rootfs/work
 mkdir -p /mnt/opt/X11/merged
@@ -21,7 +24,7 @@ if [ $? != 0 ]; then
 else
 	mknod -m 0660 /dev/loop8 b 7 8
 	losetup /dev/loop8 /mnt/opt/X11/base/xorg.img
-	mount -t ext4 -o ro /dev/loop9 /opt/X11/base/rootfs
+	mount -t ext4 -o ro /dev/loop8 /mnt/opt/X11/base/rootfs
 fi
 
 # Mounting VNC/touch input rootfs
@@ -31,18 +34,16 @@ if [ $? != 0 ]; then
 	echo "false" > /mnt/boot/flags/X11_STARTED
 	exit 1
 else
-	mknod -m 0660 /dev/loop9 b 7 8
+	mknod -m 0660 /dev/loop9 b 7 9
 	losetup /dev/loop9 /mnt/opt/X11/base/vnc-touch.img
-	mount -t ext4 -o ro /dev/loop9 /opt/X11/vnc-touch
+	mount -t ext4 -o ro /dev/loop9 /mnt/opt/X11/vnc-touch
 fi
 
 # Extensions
 # Mounting extensions userstore
-mknod -m 0660 /dev/loop10 b 7 8
+mknod -m 0660 /dev/loop10 b 7 10
 losetup /dev/loop10 /mnt/opt/storage/extensions.img
-mount -t ext4 -o nosuid /dev/loop10 /mnt/opt/X11/extensions-user 2>/dev/null
-
-busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/extensions-base:/opt/X11/extensions-user" "/opt/X11/extensions"
+mount -t vfat -o nosuid /dev/loop10 /mnt/opt/X11/extensions-user 2>/dev/null
 
 # Mounting extensions
 rm /mnt/opt/X11/nographic_extensions_list 2>/dev/null
@@ -52,7 +53,7 @@ rm /mnt/opt/X11/extensions_folders_list 2>/dev/null
 
 loop_number=11
 
-for f in /mnt/opt/X11/extensions/*.isa /mnt/opt/X11/extensions/*.img ; do
+for f in /mnt/opt/X11/extensions-base/*.isa /mnt/opt/X11/extensions-base/*.img ; do
 	FILE_RAW="$f"
 	FILE=`echo "$f" | cut -d'/' -f3-`
 	FILE="/$FILE"
@@ -62,6 +63,69 @@ for f in /mnt/opt/X11/extensions/*.isa /mnt/opt/X11/extensions/*.img ; do
 	EXTENSION_FOLDER="/$EXTENSION_FOLDER"
 	EXTENSION_NAME_RAW=`echo "$EXTENSION_FOLDER" | cut -d'/' -f5-`
 	EXTENSION_NAME=`echo "$EXTENSION_NAME_RAW" | awk '{ print toupper( substr( $0, 1, 1 ) ) substr( $0, 2); }'`
+	if [ "$EXTENSION_NAME" == "*" ]; then
+		break
+	fi
+
+	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
+	if [ $? != 0 ]; then
+		busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-nographic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
+		if [ $? != 0 ]; then
+			echo "Digital signature of KoBox package '$EXTENSION_NAME' invalid! Aborting launch..."
+			echo "false" > /mnt/boot/flags/X11_STARTED
+			exit 1
+		else
+			echo "$EXTENSION_NAME" >> /mnt/opt/X11/nographic_extensions_list
+			echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/nographic_extensions_folders_list
+			busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
+	                busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+			if [ $? != 0 ]; then
+				mknod -m 0660 /dev/loop$loop_number b 7 $loop_number
+				losetup /dev/loop$loop_number "$FILE_RAW"
+				mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
+				loop_number=$((loop_number+1))
+				if [ $? != 0 ]; then
+					echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
+					echo "false" > /mnt/boot/flags/X11_STARTED
+					exit 1
+				fi
+			fi
+	                UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+		fi
+	else
+		echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
+		echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
+
+		busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
+		busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+		if [ $? != 0 ]; then
+			mknod -m 0660 /dev/loop$loop_number b 7 $loop_number
+			losetup /dev/loop$loop_number "$FILE_RAW"
+			mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
+			loop_number=$((loop_number+1))
+			if [ $? != 0 ]; then
+				echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
+				echo "false" > /mnt/boot/flags/X11_STARTED
+				exit 1
+			fi
+		fi
+		UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+	fi
+done
+
+for f in /mnt/opt/X11/extensions-user/*.isa /mnt/opt/X11/extensions-user/*.img ; do
+	FILE_RAW="$f"
+	FILE=`echo "$f" | cut -d'/' -f3-`
+	FILE="/$FILE"
+	FILE_DGST="$FILE.dgst"
+	EXTENSION_FOLDER_RAW=`echo "$f" | cut -d'.' -f1`
+	EXTENSION_FOLDER=`echo "$EXTENSION_FOLDER_RAW" | cut -d'/' -f3-`
+	EXTENSION_FOLDER="/$EXTENSION_FOLDER"
+	EXTENSION_NAME_RAW=`echo "$EXTENSION_FOLDER" | cut -d'/' -f5-`
+	EXTENSION_NAME=`echo "$EXTENSION_NAME_RAW" | awk '{ print toupper( substr( $0, 1, 1 ) ) substr( $0, 2); }'`
+	if [ "$EXTENSION_NAME" == "*" ]; then
+		break
+	fi
 
 	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
 	if [ $? != 0 ]; then
@@ -108,13 +172,19 @@ for f in /mnt/opt/X11/extensions/*.isa /mnt/opt/X11/extensions/*.img ; do
 		UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
 	fi
 done
+
 UNIONFS_FOLDERS="${UNIONFS_FOLDERS_RAW::-1}"
 
 # Mounting extensions UnionFS-FUSE merge point
-busybox chroot /mnt "/usr/local/bin/unionfs" "$UNIONFS_FOLDERS" "/opt/X11/extensions/merged"
+mkdir -p /mnt/opt/X11/extensions-merged
+busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/extensions-base:/opt/X11/extensions-user" "/opt/X11/extension-storage-merged"
+# Replacing 'user' and 'base' strings with 'merged' so we can mount them after
+UNIONFS_FOLDERS=`echo "$UNIONFS_FOLDERS" | sed 's/extensions-base/extension-storage-merged/' | sed 's/extensions-user/extension-storage-merged/'`
+busybox chroot /mnt "/usr/local/bin/unionfs" "$UNIONFS_FOLDERS" "/opt/X11/extensions-merged"
+
 
 # Merging X11 rootfs and extensions filesystem together
-busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/base/rootfs:/opt/X11/extensions/merged" "/opt/X11/merged"
+busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/base/rootfs:/opt/X11/extensions-merged" "/opt/X11/merged"
 
 # Making the union mount read/write and mounting the final overlay to /xorg
 busybox chroot /mnt "/bin/fuse-overlayfs" "-o" "lowerdir=/opt/X11/merged,upperdir=/opt/X11/rootfs/write,workdir=/opt/X11/rootfs/work" "/xorg"
