checksum-verify improvements

diff --git a/initrd/common/startx b/initrd/common/startx
--- a/initrd/common/startx
+++ b/initrd/common/startx
@@ -8,31 +8,6 @@ if grep -q "true" /mnt/opt/developer/key/valid-key &>/dev/null; then
 	mount --bind /tmp/fake-openssl /mnt/usr/bin/openssl
 fi
 
-checksum_verify() {
-	SERVER="pkgs.kobox.fermino.me"
-	DEVICE=$(cat /opt/device 2>/dev/null)
-	VERSION=$(cat /mnt/opt/version 2>/dev/null)i
-	PACKAGE="${1}"
-	IS_CONNECTED=$(cat /tmp/wifi_connected 2>/dev/null)
-	if [ "${IS_CONNECTED}" != "true" ]; then
-		return 1
-	else
-		# Trying firmware relase checksums
-		wget -O - "http://${SERVER}/keyserver/device/${DEVICE}/packages/${VERSION}/${PACKAGE}.sha256"
-		# If not found, then try with KoBox checksums
-		if [ "${?}" != 0 ]; then
-			wget -O - "http://${SERVER}/keyserver/device/${DEVICE}/packages/kobox/${PACKAGE}.sha256"
-			if [ "${?}" != 0 ]; then
-				return 127
-			else
-				return 0
-			fi
-		else
-			return 0
-		fi
-	fi
-}
-
 echo
 echo "Starting X11 windowing system ..."
 
@@ -60,7 +35,7 @@ losetup /dev/loop2 /mnt/opt/storage/X11/base.img
 mount -t ext4 -o ro /dev/loop2 /mnt/opt/X11/base
 
 # Mounting X11 rootfs read-only with squashfuse
-checksum_verify /mnt/opt/X11/base/xorg.img
+/bin/checksum-verify /mnt/opt/X11/base/xorg.img
 if [ "$?" != 0 ]; then
 	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "/opt/X11/base/xorg.img.dgst" "/opt/X11/base/xorg.img" &>/dev/null
 	if [ $? != 0 ]; then
@@ -79,7 +54,7 @@ else
 fi
 
 # Mounting VNC/touch input rootfs
-checksum_verify /mnt/opt/X11/base/vnc-touch.img
+/bin/checksum-verify /mnt/opt/X11/base/vnc-touch.img
 if [ $? != 0 ]; then
 	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "/opt/X11/base/vnc-touch.img.dgst" "/opt/X11/base/vnc-touch.img" &>/dev/null
 	if [ $? != 0 ]; then
@@ -134,7 +109,7 @@ for f in /mnt/opt/X11/extensions-base/*.isa /mnt/opt/X11/extensions-base/*.img ;
 		break
 	fi
 
-	checksum_verify "$f"
+	/bin/checksum-verify "$f"
 	if [ $? != 0 ]; then
 		busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
 		if [ $? != 0 ]; then
@@ -147,12 +122,12 @@ for f in /mnt/opt/X11/extensions-base/*.isa /mnt/opt/X11/extensions-base/*.img ;
 				echo "$EXTENSION_NAME" >> /mnt/opt/X11/nographic_extensions_list
 				echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/nographic_extensions_folders_list
 				busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
-		                busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+				busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
 				if [ $? != 0 ]; then
 					mknod -m 0660 /dev/loop$loop_number b 7 $loop_number
 					losetup /dev/loop$loop_number "$FILE_RAW"
-					mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 					loop_number=$((loop_number+1))
+					mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 					if [ $? != 0 ]; then
 						echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
 						echo "false" > /mnt/boot/flags/X11_STARTED
@@ -170,8 +145,8 @@ for f in /mnt/opt/X11/extensions-base/*.isa /mnt/opt/X11/extensions-base/*.img ;
 			if [ $? != 0 ]; then
 				mknod -m 0660 /dev/loop$loop_number b 7 $loop_number
 				losetup /dev/loop$loop_number "$FILE_RAW"
-				mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 				loop_number=$((loop_number+1))
+				mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 				if [ $? != 0 ]; then
 					echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
 					echo "false" > /mnt/boot/flags/X11_STARTED
@@ -199,30 +174,51 @@ for f in /mnt/opt/X11/extensions-user/*.isa /mnt/opt/X11/extensions-user/*.img ;
 		break
 	fi
 
-	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
+	/bin/checksum-verify "$f"
 	if [ $? != 0 ]; then
-		busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-nographic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
+		busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
 		if [ $? != 0 ]; then
-			echo "Digital signature of KoBox package '$EXTENSION_NAME' invalid! Aborting launch..."
-			echo "false" > /mnt/boot/flags/X11_STARTED
-			exit 1
+			busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-nographic-public.pem" "-signature" "$FILE_DGST" "$FILE" &>/dev/null
+			if [ $? != 0 ]; then
+				echo "Digital signature of KoBox package '$EXTENSION_NAME' invalid! Aborting launch..."
+				echo "false" > /mnt/boot/flags/X11_STARTED
+				exit 1
+			else
+				echo "$EXTENSION_NAME" >> /mnt/opt/X11/nographic_extensions_list
+				echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/nographic_extensions_folders_list
+				busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
+		                busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+				if [ $? != 0 ]; then
+					mknod -m 0660 /dev/loop$loop_number b 7 8
+					losetup /dev/loop$loop_number "$FILE_RAW"
+					loop_number=$((loop_number+1))
+					mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
+					if [ $? != 0 ]; then
+						echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
+						echo "false" > /mnt/boot/flags/X11_STARTED
+						exit 1
+					fi
+				fi
+		                UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+			fi
 		else
-			echo "$EXTENSION_NAME" >> /mnt/opt/X11/nographic_extensions_list
-			echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/nographic_extensions_folders_list
+			echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
+			echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
+	
 			busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
-	                busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+			busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
 			if [ $? != 0 ]; then
 				mknod -m 0660 /dev/loop$loop_number b 7 8
 				losetup /dev/loop$loop_number "$FILE_RAW"
-				mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 				loop_number=$((loop_number+1))
+				mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 				if [ $? != 0 ]; then
 					echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
 					echo "false" > /mnt/boot/flags/X11_STARTED
 					exit 1
 				fi
 			fi
-	                UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+			UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
 		fi
 	else
 		echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
@@ -233,8 +229,8 @@ for f in /mnt/opt/X11/extensions-user/*.isa /mnt/opt/X11/extensions-user/*.img ;
 		if [ $? != 0 ]; then
 			mknod -m 0660 /dev/loop$loop_number b 7 8
 			losetup /dev/loop$loop_number "$FILE_RAW"
-			mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 			loop_number=$((loop_number+1))
+			mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
 			if [ $? != 0 ]; then
 				echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
 				echo "false" > /mnt/boot/flags/X11_STARTED
@@ -253,7 +249,6 @@ busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/extensions-base:/opt/X11/
 # Replacing 'user' and 'base' strings with 'merged' so we can mount them after
 UNIONFS_FOLDERS=`echo "$UNIONFS_FOLDERS" | sed 's/extensions-base/extension-storage-merged/' | sed 's/extensions-user/extension-storage-merged/'`
 busybox chroot /mnt "/usr/local/bin/unionfs" "$UNIONFS_FOLDERS" "/opt/X11/extensions-merged"
-
 
 # Merging X11 rootfs and extensions filesystem together
 busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/base/rootfs:/opt/X11/extensions-merged" "/opt/X11/merged"
@@ -294,6 +289,7 @@ mount --bind /tmp/resolv.conf /mnt/opt/X11/vnc-touch/etc/resolv.conf
 
 echo "true" > /mnt/boot/flags/X11_STARTED
 
+# Race condition
 sleep 8
 echo "Done."
 
