startx: Actually mount extension after checksum-verify

diff --git a/initrd/common/startx b/initrd/common/startx
--- a/initrd/common/startx
+++ b/initrd/common/startx
@@ -156,7 +156,24 @@ for f in /mnt/opt/X11/extensions-base/*.isa /mnt/opt/X11/extensions-base/*.img ;
 			UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
 		fi
 	else
-		echo "Verification succeeded (SHA256)"
+		echo "$FILE: Verification succeeded (SHA256)"
+		echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
+		echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
+
+		busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
+		busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER" 2>/dev/null
+		if [ $? != 0 ]; then
+			mknod -m 0660 /dev/loop$loop_number b 7 $loop_number
+			losetup /dev/loop$loop_number "$FILE_RAW"
+			mount -t ext4 -o ro "/dev/loop$loop_number" "$EXTENSION_FOLDER_RAW"
+			if [ $? != 0 ]; then
+				echo "Extension $EXTENSION_NAME is not valid! Aborting launch..."
+				echo "false" > /mnt/boot/flags/X11_STARTED
+				exit 1
+			fi
+			loop_number=$((loop_number+1))
+		fi
+		UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
 	fi
 done
 
@@ -221,6 +238,7 @@ for f in /mnt/opt/X11/extensions-user/*.isa /mnt/opt/X11/extensions-user/*.img ;
 			UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
 		fi
 	else
+		echo "$FILE: Verification succeeded (SHA256)"
 		echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
 		echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
 
