Implemented OpenSSL verification for KoBox packages

diff --git a/initrd/common/startx b/initrd/common/startx
--- a/initrd/common/startx
+++ b/initrd/common/startx
@@ -13,32 +13,62 @@ mkdir -p /mnt/opt/X11/vnc-touch
 mkdir -p /mnt/opt/X11/update
 
 # Mounting X11 rootfs read-only with squashfuse
-busybox chroot /mnt "/bin/squashfuse" "/opt/X11/base/xorg.isa" "/opt/X11/base/rootfs"
+busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "/opt/X11/base/xorg.isa.dgst" "/opt/X11/base/xorg.isa"
+if [ $? != 0 ]; then
+	echo "KoBox base rootfs package's signature is invalid! Aborting launch..."
+	echo "false" > /mnt/boot/flags/X11_STARTED
+	exit 1
+else
+	busybox chroot /mnt "/bin/squashfuse" "/opt/X11/base/xorg.isa" "/opt/X11/base/rootfs"
+fi
 
 # Mounting VNC/touch input rootfs
-busybox chroot /mnt "/bin/squashfuse" "/opt/X11/base/vnc-touch.isa" "/opt/X11/vnc-touch"
+busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "/opt/X11/base/vnc-touch.isa.dgst" "/opt/X11/base/vnc-touch.isa"
+if [ $? != 0 ]; then
+	echo "VNC/touch input rootfs package's signature is invalid! Aborting launch..."
+	echo "false" > /mnt/boot/flags/X11_STARTED
+	exit 1
+else
+	busybox chroot /mnt "/bin/squashfuse" "/opt/X11/base/vnc-touch.isa" "/opt/X11/vnc-touch"
+fi
 
 # Extensions
 # Mounting extensions userstore
-mount /mnt/opt/storage/extensions.img /mnt/opt/X11/extensions
+mount /mnt/opt/storage/extensions.img /mnt/opt/X11/extensions 2>/dev/null
 # Mounting extensions
+rm /mnt/opt/X11/nographic_extensions_list
+rm /mnt/opt/X11/nographic_extensions_folders_list
 rm /mnt/opt/X11/extensions_list
 rm /mnt/opt/X11/extensions_folders_list
 for f in /mnt/opt/X11/extensions/*.isa ; do
 	FILE=`echo "$f" | cut -d'/' -f3-`
 	FILE="/$FILE"
+	FILE_DGST="$FILE.dgst"
 	EXTENSION_FOLDER_RAW=`echo "$f" | cut -d'.' -f1`
 	EXTENSION_FOLDER=`echo "$EXTENSION_FOLDER_RAW" | cut -d'/' -f3-`
 	EXTENSION_FOLDER="/$EXTENSION_FOLDER"
 	EXTENSION_NAME_RAW=`echo "$EXTENSION_FOLDER" | cut -d'/' -f5-`
 	EXTENSION_NAME=`echo "$EXTENSION_NAME_RAW" | awk '{ print toupper( substr( $0, 1, 1 ) ) substr( $0, 2); }'`
 
-	echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
-	echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
+	busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-graphic-public.pem" "-signature" "$FILE_DGST" "$FILE"
+	if [ $? != 0 ]; then
+		busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/kobox-nographic-public.pem" "-signature" "$FILE_DGST" "$FILE"
+		if [ $? != 0 ]; then
+			echo "Digital signature of KoBox package '$EXTENSION_NAME' invalid! Aborting launch..."
+			echo "false" > /mnt/boot/flags/X11_STARTED
+			exit 1
+		else
+			echo "$EXTENSION_NAME" >> /mnt/opt/X11/nographic_extensions_list
+			echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/nographic_extensions_folders_list
+		fi
+	else
+		echo "$EXTENSION_NAME" >> /mnt/opt/X11/extensions_list
+		echo "$EXTENSION_FOLDER" >> /mnt/opt/X11/extensions_folders_list
 
-	busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
-	busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER"
-	UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+		busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
+		busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER"
+		UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
+	fi
 done
 UNIONFS_FOLDERS="${UNIONFS_FOLDERS_RAW::-1}"
 
@@ -85,5 +115,7 @@ mount -t proc proc /mnt/opt/X11/vnc-touch/proc
 mount -t devpts devpts /mnt/opt/X11/vnc-touch/dev/pts
 touch /mnt/etc/resolv.conf
 mount --bind /mnt/etc/resolv.conf /mnt/opt/X11/vnc-touch/etc/resolv.conf
+
+echo "true" > /mnt/boot/flags/X11_STARTED
 
 sleep 15
